name: jo
version: "1.2"
summary: jo
description: |
  This is jo, a small utility to create JSON objects or arrays.

confinement: strict
grade: stable

apps:
  jo:
    command: jo
    plugs: [home, removable-media]

parts:
  jo:
    plugin: autotools
    source-type: git
    source: https://github.com/jpmens/jo
